version: '3.8'

services:
  
  db:
    container_name: postgres
    image: postgres:10.8
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-data: